build_from:
  aarch64: ghcr.io/hassio-addons/base-aarch64:15.0.7
  amd64: ghcr.io/hassio-addons/base-amd64:15.0.7
  armhf: ghcr.io/hassio-addons/base-armhf:15.0.7
  armv7: ghcr.io/hassio-addons/base-armv7:15.0.7
  i386: ghcr.io/hassio-addons/base-i386:15.0.7
labels:
  org.opencontainers.image.title: "Heimdall"
  org.opencontainers.image.description: "An Application Dashboard and Launcher"
  org.opencontainers.image.source: "https://github.com/yourusername/heimdall-hassio-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  HEIMDALL_VERSION: "2.6.1"
