name: Heimdall
version: "2.6.1"
slug: heimdall
description: An Application Dashboard and Launcher
url: https://github.com/yourusername/heimdall-hassio-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: lscr.io/linuxserver/heimdall:latest
init: false
map:
  - share:rw
  - ssl:ro
options:
  PUID: 99
  PGID: 100
  TZ: UTC
schema:
  PUID: int(1,65534)
  PGID: int(1,65534)
  TZ: str
ports:
  80/tcp: 7880
  443/tcp: 7443
ports_description:
  80/tcp: HTTP port for Heimdall
  443/tcp: HTTPS port for Heimdall (SSL only)
webui: http://[HOST]:[PORT:80]
panel_icon: mdi:view-dashboard
startup: application
boot: auto
hassio_api: false
hassio_role: default
homeassistant_api: false
host_network: false
privileged: []
full_access: false
apparmor: true
devicetree: false
environment:
  PUID: "99"
  PGID: "100"
  TZ: "UTC"
tmpfs: false
