name: Heimdall
version: "2.6.1"
slug: heimdall
description: An Application Dashboard and Launcher
url: https://github.com/MeighenHouse/heimdall-hassio-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - ssl:ro
options:
  http_port: 80
  https_port: 443
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  http_port: int(1,65535)
  https_port: int(1,65535)
  ssl: bool
  certfile: str
  keyfile: str
ports:
  80/tcp: null
  443/tcp: null
ports_description:
  80/tcp: HTTP port for Heimdall
  443/tcp: HTTPS port for Heimdall (SSL only)
webui: http://[HOST]:[PORT:80]
panel_icon: mdi:view-dashboard
startup: application
boot: auto
hassio_api: false
hassio_role: default
homeassistant_api: false
host_network: false
privileged: []
full_access: false
apparmor: true
devicetree: false
