name: "Heimdall"
version: "1.0.1"
slug: "heimdall"
description: "Heimdall dashboard for Home Assistant"
url: "https://github.com/linuxserver/Heimdall"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 80
# Optional: still expose ports for direct access
ports:
  80/tcp: 80
ports_description:
  80/tcp: "Web interface (HTTP)"
# Map persistent storage - try both formats
map:
  - "config:rw"
# Alternative format if above doesn't work:
# map:
#   - config
options: {}
schema: {}
